### ISSUE TITLE
Pip version is way out of date

### ISSUE THREAD

**Issue by litchfield** [pythonforfacebook/facebook-sdk#207] opened 2015-04-15 23:54 UTC
Doesn't even support the version= parameter in the docs

**Comment by martey** [comment] 2015-04-15 23:57
Please search before opening new issues. This is a duplicate of #192.

**Closed by martey** 2015-04-15 23:57 UTC

**Comment by litchfield** [comment] 2015-04-16 00:09
Dude. This issue isn’t solved….. the pip version is still out of date….. and I can’t find your group post (nor do I care about it)…… how about you just update it?


Simon Litchfield
+61-416-027-826
