### ISSUE TITLE
Release a new version to pypi 

### ISSUE THREAD

**Issue by ktaragorn** [pythonforfacebook/facebook-sdk#238] opened 2015-09-15 09:29 UTC
0.4.0 was released maybe 3 years ago, and there have been so much changes to the code.. It is high time for 0.5 or 1.0 release

**Comment by martey** [comment] 2015-09-15 09:41
Since this is not a bug, and since this has already been discussed extensively in previous Github issues and in https://groups.google.com/d/topic/pythonforfacebook/Xxj1u22yNXU/discussion, closing and locking this issue.

**Closed by martey** 2015-09-15 09:41 UTC
