### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by sherkt** [pythonforfacebook/facebook-sdk#221] opened 2015-06-02 02:41 UTC
I get the following TypeError: the JSON object must be str, not 'bytes'

This is happening in the parse_signed_request() method, which is called when I do this:
user = facebook.get_user_from_cookie(cookies, APP_ID, APP_SECRET)

I am able to fix this by making the following change:

data = json.loads(data)
to
data = json.loads(data.decode('utf-8'))

Do you know why I might be having this problem and have to do the decode?

Thanks.

**Comment by martey** [comment] 2015-06-02 08:27
This looks like a duplicate of #209.

**Closed by martey** 2015-06-02 08:27 UTC
